/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.maven.plugins.help;

import java.io.StringWriter;
import java.nio.charset.Charset;
import java.util.Properties;

import org.codehaus.plexus.util.StringUtils;
import org.codehaus.plexus.util.xml.PrettyPrintXMLWriter;
import org.codehaus.plexus.util.xml.XMLWriter;
import org.codehaus.plexus.util.xml.XmlWriterUtil;
import org.junit.jupiter.api.Test;

import static java.lang.String.format;
import static org.junit.jupiter.api.Assertions.assertEquals;

class EffectiveMojoUtilsTest {

    private final StringWriter w = new StringWriter();
    private final String encoding = Charset.defaultCharset().displayName();
    private final XMLWriter writer = new PrettyPrintXMLWriter(
            w, StringUtils.repeat(" ", XmlWriterUtil.DEFAULT_INDENTATION_SIZE), encoding, null);

    @Test
    void writeHeaderShouldWriteHeaderComments() {
        EffectiveMojoUtils.writeHeader(writer);

        assertEquals(
                format("<?xml version=\"1.0\" encoding=\"%s\"?>%n", encoding)
                        + format("<!-- ====================================================================== -->%n")
                        + format("<!--                                                                        -->%n")
                        + format("<!-- Generated by Maven Help Plugin                                         -->%n")
                        + format("<!-- See: https://maven.apache.org/plugins/maven-help-plugin/               -->%n")
                        + format("<!--                                                                        -->%n")
                        + format("<!-- ====================================================================== -->%n"),
                w.toString());
    }

    @Test
    void writeCommentShouldWriteGivenComment() {
        EffectiveMojoUtils.writeComment(writer, "This is a comment");

        assertEquals(
                format("<?xml version=\"1.0\" encoding=\"%s\"?>%n", encoding)
                        + format("<!-- ====================================================================== -->%n")
                        + format("<!--                                                                        -->%n")
                        + format("<!-- This is a comment                                                      -->%n")
                        + format("<!--                                                                        -->%n")
                        + format("<!-- ====================================================================== -->%n"),
                w.toString());
    }

    @Test
    void sortPropertiesShouldSortProperties() {
        final Properties props = new Properties();
        props.setProperty("z", "last");
        props.setProperty("a", "first");
        props.setProperty("g", "middle");

        final Properties sortedProps = EffectiveMojoUtils.sortProperties(props);

        final Object[] sortedValues = sortedProps.values().toArray();
        assertEquals("first", sortedValues[0]);
        assertEquals("middle", sortedValues[1]);
        assertEquals("last", sortedValues[2]);

        final Object[] sortedKeys = sortedProps.keySet().toArray();
        assertEquals("a", sortedKeys[0]);
        assertEquals("g", sortedKeys[1]);
        assertEquals("z", sortedKeys[2]);
    }

    @Test
    void prettyFormatShouldFormatXmlString() {
        final String xml = "<root><child><subchild>value</subchild></child></root>";

        final String prettyXml = EffectiveMojoUtils.prettyFormat(xml, encoding, false);

        assertEquals(
                format("<?xml version=\"1.0\" encoding=\"%s\"?>%n", encoding)
                        + format("<root>%n")
                        + format("  <child>%n")
                        + format("    <subchild>value</subchild>%n")
                        + format("  </child>%n")
                        + format("</root>%n"),
                prettyXml);
    }

    @Test
    void prettyFormatShouldOmitDeclarationWhenSpecified() {
        final String xml = "<root><child><subchild>value</subchild></child></root>";

        final String prettyXml = EffectiveMojoUtils.prettyFormat(xml, encoding, true);

        assertEquals(
                format("<root>%n")
                        + format("  <child>%n")
                        + format("    <subchild>value</subchild>%n")
                        + format("  </child>%n")
                        + format("</root>%n"),
                prettyXml);
    }
}
