package org.apache.maven.plugins.help;

import org.codehaus.plexus.util.StringUtils;
import org.codehaus.plexus.util.xml.PrettyPrintXMLWriter;
import org.codehaus.plexus.util.xml.XMLWriter;
import org.codehaus.plexus.util.xml.XmlWriterUtil;
import org.junit.jupiter.api.Test;

import java.io.StringWriter;
import java.nio.charset.Charset;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertEquals;

class EffectiveMojoUtilsTest {

    private final StringWriter w = new StringWriter();
    private final String encoding = Charset.defaultCharset().displayName();
    private final XMLWriter writer = new PrettyPrintXMLWriter(w, StringUtils.repeat(" ", XmlWriterUtil.DEFAULT_INDENTATION_SIZE), encoding, null);


    @Test
    void writeHeader_shouldWriteHeaderComments() {
        EffectiveMojoUtils.writeHeader(writer);

        assertEquals(String.format("<?xml version=\"1.0\" encoding=\"%s\"?>\n", encoding) +
                        "<!-- ====================================================================== -->\n" +
                        "<!--                                                                        -->\n" +
                        "<!-- Generated by Maven Help Plugin                                         -->\n" +
                        "<!-- See: https://maven.apache.org/plugins/maven-help-plugin/               -->\n" +
                        "<!--                                                                        -->\n" +
                        "<!-- ====================================================================== -->\n",
                w.toString());
    }

    @Test
    void writeComment_shouldWriteGivenComment() {
        EffectiveMojoUtils.writeComment(writer, "This is a comment");

        assertEquals(String.format("<?xml version=\"1.0\" encoding=\"%s\"?>\n", encoding) +
                        "<!-- ====================================================================== -->\n" +
                        "<!--                                                                        -->\n" +
                        "<!-- This is a comment                                                      -->\n" +
                        "<!--                                                                        -->\n" +
                        "<!-- ====================================================================== -->\n",
                w.toString());
    }

    @Test
    void sortProperties_shouldSortProperties() {
        final Properties props = new Properties();
        props.setProperty("z", "last");
        props.setProperty("a", "first");
        props.setProperty("g", "middle");

        final Properties sortedProps = EffectiveMojoUtils.sortProperties(props);

        final Object[] sortedValues = sortedProps.values().toArray();
        assertEquals("first", sortedValues[0]);
        assertEquals("middle", sortedValues[1]);
        assertEquals("last", sortedValues[2]);

        final Object[] sortedKeys = sortedProps.keySet().toArray();
        assertEquals("a", sortedKeys[0]);
        assertEquals("g", sortedKeys[1]);
        assertEquals("z", sortedKeys[2]);
    }

    @Test
    void prettyFormat_shouldFormatXmlString() throws Exception {
        final String xml = "<root><child><subchild>value</subchild></child></root>";

        final String prettyXml = EffectiveMojoUtils.prettyFormat(xml, encoding, false);

        assertEquals("<?xml version=\"1.0\" encoding=\"" + encoding + "\"?>\n" +
                "<root>\n" +
                "  <child>\n" +
                "    <subchild>value</subchild>\n" +
                "  </child>\n" +
                "</root>\n", prettyXml);
    }

    @Test
    void prettyFormat_shouldOmitDeclarationWhenSpecified() throws Exception {
        final String xml = "<root><child><subchild>value</subchild></child></root>";

        final String prettyXml = EffectiveMojoUtils.prettyFormat(xml, encoding, true);

        assertEquals("<root>\n" +
                "  <child>\n" +
                "    <subchild>value</subchild>\n" +
                "  </child>\n" +
                "</root>\n", prettyXml);
    }
}